// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7u5qpawIeB3M5h8QchjE3GC85-ua6yA',
    appId: '1:990014770353:web:78d11e0b026fe6a5f3a690',
    messagingSenderId: '990014770353',
    projectId: 'apps-collection-8a710',
    authDomain: 'apps-collection-8a710.firebaseapp.com',
    storageBucket: 'apps-collection-8a710.firebasestorage.app',
    measurementId: 'G-FM2J1LKQKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9y2SXJihaefwW4Tvq3TTBw5khMFdqcWE',
    appId: '1:990014770353:android:822b5b70a44c5ba3f3a690',
    messagingSenderId: '990014770353',
    projectId: 'apps-collection-8a710',
    storageBucket: 'apps-collection-8a710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNvwOHDMf1jujc8qIjoCJjAWUg_zx-Og',
    appId: '1:990014770353:ios:0d75ab3cec57494bf3a690',
    messagingSenderId: '990014770353',
    projectId: 'apps-collection-8a710',
    storageBucket: 'apps-collection-8a710.firebasestorage.app',
    iosBundleId: 'com.example.apiClass',
  );
}
